import localFont from "next/font/local";
import "./globals.css";
import CommonLayout from "@/components/common-layout";
import { currentUser, fetchUser } from "@/actions";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await currentUser();
  const ProfileUser = await fetchUser(user?.userId);
  return (
    <html lang="en">
      <body>
        <CommonLayout user={user} ProfileUser={ProfileUser}>
          {children}
        </CommonLayout>
      </body>
    </html>
  );
}
